## 프로그램 오류

---

- 컴파일 에러  :컴파일 할 때 발생하는 에러
    - 자바 컴파일러가 구문체크, 번역, 최적화 정도 수행한다.
- 런타임 에러 : 실행 할 때 발생하는 에러
    - 에러 : 수습될 수 없는 심각한 오류
        
        → OutOfMemory
        
    - 예외 : 수습될 수 있는 다소 미약한 오류
        
        → NullPointException
        
- 논리적 에러 : 작성 의도와 다르게 동작

### 에러는 어쩔 수 없지만, 예외는 처리하자.

**❓ 예외처리란**

프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 것

Exception 클래스들 : 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외

RuntimeException 클래스들 : 프로그래머의 실수로 발생하는 예외

![image](https://user-images.githubusercontent.com/53300830/177673624-ec9dfb42-dd0e-4bce-8268-38d9145a6ed9.png)

![image](https://user-images.githubusercontent.com/53300830/177673642-dc27131b-bac3-4fc3-993b-f9aaf8d66764.png)

## 예외처리

---

### 예외 처리하기. try-catch문

```java
try{
	// 예외가 발생할 수도 있는 코드 
} catch (오류1 오류1){
	// 오류1이 발생했을 경우 이를 처리하기 위한 문장을 적는다.
} catch (오류2 오류2){
	// 오류2이 발생했을 경우 이를 처리하기 위한 문장을 적는다.
}
```

**try블럭 내에서 예외가 발생한 경우**

- 발생한 예외와 일치하는 catch 블럭이 있는지 확인
- 일치하는 catch 블럭을 찾게 되면 그 catch블럭 내의 문장들을 수행하고 전체 try-catch 문을 빠져나가서 그 다음 문장을 계속해서 수행한다.
- 만일 일치하는 catch 블럭을 찾지 못하면, 예외는 처리하지 못한다.

**try 블럭 내에서 예외가 발생하지 않은 경우**

- catch블럭을 거치지 않고 try-catch문을 빠져나가서 수행을 계속한다.

```java
public class Ex8_4 {
    public static void main(String[] args) {
        System.out.println(1);
        System.out.println(2);

        try{
            System.out.println(3);
            System.out.println(0 / 0);
            System.out.println(4); // 실행되지 않는다.
        } catch (ArithmeticException ae){
            if(ae instanceof Exception)
                System.out.println(true);
            System.out.println("ArithmeticException");
				// 혹시 모를 오류를 대비해서 마지막에 Exception으로 막는 것도 좋은 방법이다.
        } catch (Exception e){ // 위의 catch 문에서 이미 오류가 잡혔으므로 실행되지 않는다.
            System.out.println("Exception");
        }
        System.out.println(5);
    }
}
```

## printStackTrace(), 멀티 catch 블럭

---

### printStackTrace()와 getMessage()

printStackTrace() : 예외 발생 당시 호출 스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.

getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

```java
public class Ex8_5 {
    public static void main(String[] args) {
        System.out.println(1);
        System.out.println(2);

        try{
            System.out.println(3);
            System.out.println(0 / 0);
            System.out.println(4); // 실행되지 않는다.
        } catch (ArithmeticException ae){
            ae.printStackTrace();
            System.out.println("ae.getMessage() = " + ae.getMessage());
            /*
            java.lang.ArithmeticException: / by zero
            at 자바의정석.ch8.Ex8_5.main(Ex8_5.java:10)
            ae.getMessage() = / by zero
            */
        } 
        System.out.println(5);
    }
}
```

### 멀티 catch 블럭

```java
try {
} catch (ExceptionA || ExceptionB b{
	e.printStackTrace();
}
```

- 근데 만약 부모 자식 관계일때는?
    - 부모 예외처리만 해주면 자식도 된다.
- EceptionA와 ExceptionB 가 있을 때 A에만 있는 메서드를 호출하면 B가 오류가 생겼을때 오히려 오류가 생기게 된다.
    - 즉 공통 멤버만 사용해야만 한다.

### 예외 발생하기

1. new 연산자를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
    
    `Exception e = new Exception(”고의로 발생");`
    
2. 키워드 throw를 이용해서 예외를 발생시킨다.
    
    `thorw e;`
    

### checked 예외, unchecked 예외

- checked 예외 : 컴파일러가 예외 처리 여부를 체크(예외 처리 필수)
    - Eception의 자손들
- unckecked 예외 : 컴파일러가 예외 처리 여부를 체크 안함 (예외 처리 선택)
    - RuntimeException의 자손들

```java
public class Ex8_7 {
    public static void main(String[] args) {
        // Unhandled exception: java.lang.Exception
        // 예외처리가 필수이다. 컴파일 과정에서 에러 (checked 예외)
        throw new Exception();
        try {
            // 예외 처리 안할 경우 (unckecked 예외)
            // Exception in thread "main" java.lang.RuntimeException
            throw new RuntimeException();
        } catch (RuntimeException e) {
        }
    }
}
```

## 예외 선언하기, finally 블럭

---

- 예외를 처리하는 방법 : try-catch(직접 처리), 예외 선언하기(예외 떠넘기기 → 알리기)
- 메서드가 호출시 발생가능한 예외를 호출하는 쪽에 알리는 거
    
    ```java
    void method() throws Exception1, Exception2, Exception3{} 
    ```
    

```java
import java.io.*;

class Ex8_10 {
    public static void main(String[] args) {
        try {
            File f = createFile("ljh");
            System.out.println( f.getName()+"파일이 성공적으로 생성되었습니다.");
        } catch (Exception e) {
            System.out.println(e.getMessage()+" 다시 입력해 주시기 바랍니다.");
        }
    }	// main메서드의 끝
		
    static File createFile(String fileName) throws Exception {
        if (fileName==null || fileName.equals(""))
            throw new Exception("파일이름이 유효하지 않습니다.");
        File f = new File(fileName);		//  File클래스의 객체를 만든다.
        // File객체의 createNewFile메서드를 이용해서 실제 파일을 생성한다.
        f.createNewFile();
        return f;		// 생성된 객체의 참조를 반환한다.
    }	// createFile메서드의 끝
}	// 클래스의 끝
```

- `createFile` 메서드에서 `fileName` 이 null 이거나 공백인 경우 `Exception` 예외를 던지게 된다.
- 이 때 두 선택지가 있다.
    - 직접 처리 (try-catch)
    - 떠넘기기 (예외 선언)
- 둘 중에서 위 코드는 떠넘기기(예외 선언)을 선택했다.
- 본인을 호출했던 코드에서 catch문이 있는지 확인 후 존재한다면 해당 catch문을 실행한다.

**만약 떠넘기지 않고 본인이 처리하겠다면 이렇게 하면 된다.**

```java
import java.io.*;

class Ex8_10 {
    public static void main(String[] args) {
        File f = createFile("ljh");
        System.out.println( f.getName()+"파일이 성공적으로 생성되었습니다.");
    }	

    static File createFile(String fileName) {
        // 떠넘기지 않고 본인이 처리하는 경우
        try{
            if (fileName==null || fileName.equals(""))
                throw new Exception();
        } catch (Exception e){
            fileName = "제목없음.txt";
        }

        //  File클래스의 객체를 만든다.
        File f = new File(fileName);		
        try {
            // File객체의 createNewFile메서드를 이용해서 실제 파일을 생성한다.
            f.createNewFile();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return f;		
    }	
}
```

### finally 블럭

예외 발생 여부와 관계 없이 수행돼야 하는 코드를 넣는다.

```java
try{
	startInstall();
	copyFiles();
	deleteTempFilse(); // 중복 코드
} catch(Exception e){
	e.printStackTrace();
	deleteTempFiles(); // 중복 코드
}

// 개선 코드
try{
	startInstall();
	copyFiles();
} catch(Exception e){
	e.printStackTrace();
} finally{
	deleteTempFiles(); // 중복 개선
}
```

## 사용자 정의 예외 만들기, 예외 던지기

---

### 사용자 정의 예외 만드는 방법

- 우리가 직접 예외 클래스를 정의할 수 있다.
- 조상은 `Exception` 과 `RuntimeException` 중에서 선택
    - `Exception` 은 사용자가 발생시키는 예외 (필수 처리)
    - `RuntimeException` 은 프로그래머의 실수로 발생시키는 예외 (선택 처리)
    
    ```java
    class MyException extends Exception{
    		MyException(String msg){
    				super(msg); // 조상인 Exception 클래스의 생성자를 호출한다.
    		}
    }
    ```
    

### 예외 되던지기

- 예외를 처리한 후에 다시 예외를 발생시키는 것
- 호출한 메서드와 호출된 메서드 양쪽에서 모두 예외처리 하는 것

```java
class Ex8_12 {
    public static void main(String[] args) {
        try  {
            method1();
        } catch (Exception e)	{
            System.out.println("main메서드에서 예외가 처리되었습니다.");
        }
    }	// main메서드의 끝

    static void method1() throws Exception {
        try {
            throw new Exception();
        } catch (Exception e) {
            System.out.println("method1메서드에서 예외가 처리되었습니다.");
            throw e;			// 다시 예외를 발생시킨다.
        }
    }	// method1메서드의 끝
}
```

해당 문제에서 예외 처리 방법은 3가지가 존재한다.

- method1에서 처리
- main에서 처리
- 둘 다 에서 처리
    - 분담처리할 때 사용할 방법이다.

## 연결된 예외

---

- 한 예외가 다른 예외를 발생시킬 수 있다.
- 예외 A가 예외 B를 발생시키면 A는 B의 원인 예외(cause exception)
    
    ```java
    Throwable initCause(Trhowable cuase) // 지정한 예외를 원인 예외로 등록
    Throwable getCause() // 원인 예외를 반환
    ```
    

### **❓ 굳이 묶어서 던질 필요가 있나?**

- 여러 예외를 하나로 묶어서 다루기 위함
    
    ```java
    static void install() throws InstallException {
        try {
            startInstall();		// 프로그램 설치에 필요한 준비를 한다.
            copyFiles();		// 파일들을 복사한다.
        } catch (SpaceException2 e)	{
            InstallException ie = new InstallException("설치 중 예외발생");
            ie.initCause(e);
            throw ie;
        } catch (MemoryException2 me) {
            InstallException ie = new InstallException("설치 중 예외발생");
            ie.initCause(me);
            throw ie;
        } finally {
            deleteTempFiles();		// 프로그램 설치에 사용된 임시파일들을 삭제한다.
        } // try의 끝
    }
    자바의정석.ch8.InstallException: 설치 중 예외발생
    at 자바의정석.ch8.Ex8_13.install(Ex8_13.java:19)
    at 자바의정석.ch8.Ex8_13.main(Ex8_13.java:6)
    Caused by: 자바의정석.ch8.SpaceException2: 설치할 공간이 부족합니다.
    at 자바의정석.ch8.Ex8_13.startInstall(Ex8_13.java:33)
    at 자바의정석.ch8.Ex8_13.install(Ex8_13.java:16)
    ```
    
- checked(Excpetion, 필수처리) 예외를 unckecked(RuntimException, 선택처리) 예외로 변경하려 할 때
